name: Package json
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        uses: npm ci
      - name: Run lint
        run: npm run lint
